### ISSUE TITLE
Show response name

### ISSUE THREAD

**Issue by MarvinJanssen** [Light-Labs/rydcon#3]
It would be nice if `rydcon` shows the response textual name behind the hex value in brackets. For example:

```
> COMMAND_WAKE
< 01 (RESPONSE_OK)
> 12
< F3 (RESPONSE_ERROR_DEPRECATED)
```

### Background

The Ryder protocol follows a simple model where the initial LISTENING state of the Ryder is changed by a single byte command. When this happens, the Ryder responds with a single-byte response indicating success or error.

After sending a response, the device will go back to a LISTENING state unless:

- It responds with `RESPONSE_SEND_INPUT`, the user should send input depending on the command. Any success or response may then follow the input. (That includes the possibility of another `RESPONSE_SEND_INPUT`.)
-  It responds with `RESPONSE_OUTPUT`, the device will then output data until the first unescaped `RESPONSE_OUTPUT_END`.
- It responds with `RESPONSE_WAIT_USER_CONFIRM`, the app should wait until the user confirms the action on screen. Once that happens, the Ryder will send a success or error response.

Success responses:

```cpp
static const uint8_t RESPONSE_OK = 1;                 // generic command ok/received
static const uint8_t RESPONSE_SEND_INPUT = 2;         // command received, send input
static const uint8_t RESPONSE_REJECTED = 3;           // user input rejected
static const uint8_t RESPONSE_OUTPUT = 4;             // sending output
static const uint8_t RESPONSE_OUTPUT_END = 5;         // end of output
static const uint8_t RESPONSE_ESC_SEQUENCE = 6;       // output esc sequence
static const uint8_t RESPONSE_WAIT_USER_CONFIRM = 10; // user has to confirm action
```

Error responses:

```cpp
static const uint8_t RESPONSE_ERROR_UNKNOWN_COMMAND = 255;
static const uint8_t RESPONSE_ERROR_NOT_INITIALISED = 254;
static const uint8_t RESPONSE_ERROR_MEMORY_ERROR = 253;
static const uint8_t RESPONSE_ERROR_APP_DOMAIN_TOO_LONG = 252;
static const uint8_t RESPONSE_ERROR_APP_DOMAIN_INVALID = 251;
static const uint8_t RESPONSE_ERROR_MNEMONIC_TOO_LONG = 250;
static const uint8_t RESPONSE_ERROR_MNEMONIC_INVALID = 249;
static const uint8_t RESPONSE_ERROR_GENERATE_MNEMONIC = 248;
static const uint8_t RESPONSE_ERROR_INPUT_TIMEOUT = 247;
static const uint8_t RESPONSE_ERROR_NOT_IMPLEMENTED = 246;
static const uint8_t RESPONSE_ERROR_INPUT_TOO_LONG = 245;
static const uint8_t RESPONSE_ERROR_INPUT_MALFORMED = 244;
static const uint8_t RESPONSE_ERROR_DEPRECATED = 243;
```

**Comment by friedger** [comment]
The same conversion could also be shown in the bridge

**Comment by pengowen123** [comment]
Fixed in [`f8c0e2`](https://github.com/Light-Labs/rydcon/commit/f8c0e2c0d8c9ee2e35b0df6741ef3784de632f03).

**Comment by friedger** [comment]
For good practise, it is better to open a pull request and close the issue with the pull request via mention of the issue.

It makes it easier to review and comment.

@pengowen123 Are these mega match constructs the only way to do this in Rust? It looks like difficult to maintain, when we add new responses in the firmware.

**Comment by pengowen123** [comment]
@friedger I'll make sure to open PRs for any fixes or major changes in the future. Would minor changes (docs, formatting, etc.) be fine to push directly to master though?

> Are these mega match constructs the only way to do this in Rust? It looks like difficult to maintain, when we add new responses in the firmware.

Good point. I could replace both with the `derive_more` crate, which might help clean up some other code as well.

**Comment by friedger** [comment]
@pengowen123  Ideally, we collect small changes in the dev branch and then make releases from main.

For rydcon, it is not too important but it can be good to just get into the habit.
